export interface Country {
  id: string;
  name: string;
  region: string;
}

export const countriesByRegion: Record<string, Country[]> = {
  "North America": [
    { id: "United States", name: "United States", region: "North America" },
    { id: "Canada", name: "Canada", region: "North America" },
    { id: "Mexico", name: "Mexico", region: "North America" },
    { id: "Guatemala", name: "Guatemala", region: "North America" },
    { id: "Belize", name: "Belize", region: "North America" },
    { id: "El Salvador", name: "El Salvador", region: "North America" },
    { id: "Honduras", name: "Honduras", region: "North America" },
    { id: "Nicaragua", name: "Nicaragua", region: "North America" },
    { id: "Costa Rica", name: "Costa Rica", region: "North America" },
    { id: "Panama", name: "Panama", region: "North America" },
  ],
  "South America": [
    { id: "Brazil", name: "Brazil", region: "South America" },
    { id: "Argentina", name: "Argentina", region: "South America" },
    { id: "Chile", name: "Chile", region: "South America" },
    { id: "Colombia", name: "Colombia", region: "South America" },
    { id: "Peru", name: "Peru", region: "South America" },
    { id: "Venezuela", name: "Venezuela", region: "South America" },
    { id: "Ecuador", name: "Ecuador", region: "South America" },
    { id: "Bolivia", name: "Bolivia", region: "South America" },
    { id: "Paraguay", name: "Paraguay", region: "South America" },
    { id: "Uruguay", name: "Uruguay", region: "South America" },
    { id: "Guyana", name: "Guyana", region: "South America" },
    { id: "Suriname", name: "Suriname", region: "South America" },
    { id: "French Guiana", name: "French Guiana", region: "South America" },
  ],
  "Europe": [
    { id: "United Kingdom", name: "United Kingdom", region: "Europe" },
    { id: "Ireland", name: "Ireland", region: "Europe" },
    { id: "France", name: "France", region: "Europe" },
    { id: "Germany", name: "Germany", region: "Europe" },
    { id: "Italy", name: "Italy", region: "Europe" },
    { id: "Spain", name: "Spain", region: "Europe" },
    { id: "Portugal", name: "Portugal", region: "Europe" },
    { id: "Netherlands", name: "Netherlands", region: "Europe" },
    { id: "Belgium", name: "Belgium", region: "Europe" },
    { id: "Switzerland", name: "Switzerland", region: "Europe" },
    { id: "Austria", name: "Austria", region: "Europe" },
    { id: "Sweden", name: "Sweden", region: "Europe" },
    { id: "Norway", name: "Norway", region: "Europe" },
    { id: "Denmark", name: "Denmark", region: "Europe" },
    { id: "Finland", name: "Finland", region: "Europe" },
    { id: "Poland", name: "Poland", region: "Europe" },
    { id: "Czech Republic", name: "Czech Republic", region: "Europe" },
    { id: "Hungary", name: "Hungary", region: "Europe" },
    { id: "Romania", name: "Romania", region: "Europe" },
    { id: "Bulgaria", name: "Bulgaria", region: "Europe" },
    { id: "Greece", name: "Greece", region: "Europe" },
    { id: "Croatia", name: "Croatia", region: "Europe" },
    { id: "Serbia", name: "Serbia", region: "Europe" },
    { id: "Slovakia", name: "Slovakia", region: "Europe" },
    { id: "Slovenia", name: "Slovenia", region: "Europe" },
    { id: "Estonia", name: "Estonia", region: "Europe" },
    { id: "Latvia", name: "Latvia", region: "Europe" },
    { id: "Lithuania", name: "Lithuania", region: "Europe" },
    { id: "Luxembourg", name: "Luxembourg", region: "Europe" },
    { id: "Malta", name: "Malta", region: "Europe" },
    { id: "Cyprus", name: "Cyprus", region: "Europe" },
    { id: "Iceland", name: "Iceland", region: "Europe" },
    { id: "Ukraine", name: "Ukraine", region: "Europe" },
    { id: "Belarus", name: "Belarus", region: "Europe" },
    { id: "Moldova", name: "Moldova", region: "Europe" },
    { id: "Albania", name: "Albania", region: "Europe" },
    { id: "Bosnia and Herzegovina", name: "Bosnia and Herzegovina", region: "Europe" },
    { id: "North Macedonia", name: "North Macedonia", region: "Europe" },
    { id: "Montenegro", name: "Montenegro", region: "Europe" },
    { id: "Russia", name: "Russia", region: "Europe" },
  ],
  "Asia": [
    { id: "China", name: "China", region: "Asia" },
    { id: "India", name: "India", region: "Asia" },
    { id: "Japan", name: "Japan", region: "Asia" },
    { id: "South Korea", name: "South Korea", region: "Asia" },
    { id: "Singapore", name: "Singapore", region: "Asia" },
    { id: "Malaysia", name: "Malaysia", region: "Asia" },
    { id: "Thailand", name: "Thailand", region: "Asia" },
    { id: "Indonesia", name: "Indonesia", region: "Asia" },
    { id: "Philippines", name: "Philippines", region: "Asia" },
    { id: "Vietnam", name: "Vietnam", region: "Asia" },
    { id: "Taiwan", name: "Taiwan", region: "Asia" },
    { id: "Hong Kong", name: "Hong Kong", region: "Asia" },
    { id: "Bangladesh", name: "Bangladesh", region: "Asia" },
    { id: "Pakistan", name: "Pakistan", region: "Asia" },
    { id: "Sri Lanka", name: "Sri Lanka", region: "Asia" },
    { id: "Nepal", name: "Nepal", region: "Asia" },
    { id: "Myanmar", name: "Myanmar", region: "Asia" },
    { id: "Cambodia", name: "Cambodia", region: "Asia" },
    { id: "Laos", name: "Laos", region: "Asia" },
    { id: "Mongolia", name: "Mongolia", region: "Asia" },
    { id: "Kazakhstan", name: "Kazakhstan", region: "Asia" },
    { id: "Uzbekistan", name: "Uzbekistan", region: "Asia" },
    { id: "Kyrgyzstan", name: "Kyrgyzstan", region: "Asia" },
    { id: "Tajikistan", name: "Tajikistan", region: "Asia" },
    { id: "Turkmenistan", name: "Turkmenistan", region: "Asia" },
    { id: "Afghanistan", name: "Afghanistan", region: "Asia" },
  ],
  "Middle East": [
    { id: "Saudi Arabia", name: "Saudi Arabia", region: "Middle East" },
    { id: "United Arab Emirates", name: "United Arab Emirates", region: "Middle East" },
    { id: "Israel", name: "Israel", region: "Middle East" },
    { id: "Qatar", name: "Qatar", region: "Middle East" },
    { id: "Kuwait", name: "Kuwait", region: "Middle East" },
    { id: "Bahrain", name: "Bahrain", region: "Middle East" },
    { id: "Oman", name: "Oman", region: "Middle East" },
    { id: "Jordan", name: "Jordan", region: "Middle East" },
    { id: "Lebanon", name: "Lebanon", region: "Middle East" },
    { id: "Iraq", name: "Iraq", region: "Middle East" },
    { id: "Iran", name: "Iran", region: "Middle East" },
    { id: "Yemen", name: "Yemen", region: "Middle East" },
    { id: "Syria", name: "Syria", region: "Middle East" },
    { id: "Palestine", name: "Palestine", region: "Middle East" },
    { id: "Turkey", name: "Turkey", region: "Middle East" },
  ],
  "Africa": [
    { id: "South Africa", name: "South Africa", region: "Africa" },
    { id: "Nigeria", name: "Nigeria", region: "Africa" },
    { id: "Kenya", name: "Kenya", region: "Africa" },
    { id: "Egypt", name: "Egypt", region: "Africa" },
    { id: "Ghana", name: "Ghana", region: "Africa" },
    { id: "Morocco", name: "Morocco", region: "Africa" },
    { id: "Tunisia", name: "Tunisia", region: "Africa" },
    { id: "Algeria", name: "Algeria", region: "Africa" },
    { id: "Ethiopia", name: "Ethiopia", region: "Africa" },
    { id: "Tanzania", name: "Tanzania", region: "Africa" },
    { id: "Uganda", name: "Uganda", region: "Africa" },
    { id: "Rwanda", name: "Rwanda", region: "Africa" },
    { id: "Senegal", name: "Senegal", region: "Africa" },
    { id: "Ivory Coast", name: "Ivory Coast", region: "Africa" },
    { id: "Cameroon", name: "Cameroon", region: "Africa" },
    { id: "Angola", name: "Angola", region: "Africa" },
    { id: "Mozambique", name: "Mozambique", region: "Africa" },
    { id: "Madagascar", name: "Madagascar", region: "Africa" },
    { id: "Zimbabwe", name: "Zimbabwe", region: "Africa" },
    { id: "Zambia", name: "Zambia", region: "Africa" },
    { id: "Botswana", name: "Botswana", region: "Africa" },
    { id: "Namibia", name: "Namibia", region: "Africa" },
    { id: "Mauritius", name: "Mauritius", region: "Africa" },
    { id: "Seychelles", name: "Seychelles", region: "Africa" },
    { id: "Libya", name: "Libya", region: "Africa" },
    { id: "Sudan", name: "Sudan", region: "Africa" },
    { id: "Mali", name: "Mali", region: "Africa" },
    { id: "Burkina Faso", name: "Burkina Faso", region: "Africa" },
    { id: "Niger", name: "Niger", region: "Africa" },
    { id: "Chad", name: "Chad", region: "Africa" },
    { id: "Mauritania", name: "Mauritania", region: "Africa" },
    { id: "Guinea", name: "Guinea", region: "Africa" },
    { id: "Sierra Leone", name: "Sierra Leone", region: "Africa" },
    { id: "Liberia", name: "Liberia", region: "Africa" },
    { id: "Togo", name: "Togo", region: "Africa" },
    { id: "Benin", name: "Benin", region: "Africa" },
    { id: "Gabon", name: "Gabon", region: "Africa" },
    { id: "Equatorial Guinea", name: "Equatorial Guinea", region: "Africa" },
    { id: "Republic of the Congo", name: "Republic of the Congo", region: "Africa" },
    { id: "Democratic Republic of the Congo", name: "Democratic Republic of the Congo", region: "Africa" },
    { id: "Central African Republic", name: "Central African Republic", region: "Africa" },
    { id: "Eritrea", name: "Eritrea", region: "Africa" },
    { id: "Djibouti", name: "Djibouti", region: "Africa" },
    { id: "Somalia", name: "Somalia", region: "Africa" },
    { id: "Malawi", name: "Malawi", region: "Africa" },
    { id: "Lesotho", name: "Lesotho", region: "Africa" },
    { id: "Eswatini", name: "Eswatini", region: "Africa" },
  ],
  "Caribbean": [
    { id: "Jamaica", name: "Jamaica", region: "Caribbean" },
    { id: "Trinidad and Tobago", name: "Trinidad and Tobago", region: "Caribbean" },
    { id: "Barbados", name: "Barbados", region: "Caribbean" },
    { id: "Bahamas", name: "Bahamas", region: "Caribbean" },
    { id: "Cuba", name: "Cuba", region: "Caribbean" },
    { id: "Dominican Republic", name: "Dominican Republic", region: "Caribbean" },
    { id: "Haiti", name: "Haiti", region: "Caribbean" },
    { id: "Puerto Rico", name: "Puerto Rico", region: "Caribbean" },
    { id: "Antigua and Barbuda", name: "Antigua and Barbuda", region: "Caribbean" },
    { id: "Aruba", name: "Aruba", region: "Caribbean" },
    { id: "Bermuda", name: "Bermuda", region: "Caribbean" },
    { id: "British Virgin Islands", name: "British Virgin Islands", region: "Caribbean" },
    { id: "Cayman Islands", name: "Cayman Islands", region: "Caribbean" },
    { id: "Dominica", name: "Dominica", region: "Caribbean" },
    { id: "Grenada", name: "Grenada", region: "Caribbean" },
    { id: "Guadeloupe", name: "Guadeloupe", region: "Caribbean" },
    { id: "Martinique", name: "Martinique", region: "Caribbean" },
    { id: "Montserrat", name: "Montserrat", region: "Caribbean" },
    { id: "Saint Kitts and Nevis", name: "Saint Kitts and Nevis", region: "Caribbean" },
    { id: "Saint Lucia", name: "Saint Lucia", region: "Caribbean" },
    { id: "Saint Vincent and the Grenadines", name: "Saint Vincent and the Grenadines", region: "Caribbean" },
    { id: "Turks and Caicos Islands", name: "Turks and Caicos Islands", region: "Caribbean" },
    { id: "US Virgin Islands", name: "US Virgin Islands", region: "Caribbean" },
  ],
  "Australasia": [
    { id: "Australia", name: "Australia", region: "Australasia" },
    { id: "New Zealand", name: "New Zealand", region: "Australasia" },
    { id: "Papua New Guinea", name: "Papua New Guinea", region: "Australasia" },
    { id: "Fiji", name: "Fiji", region: "Australasia" },
    { id: "New Caledonia", name: "New Caledonia", region: "Australasia" },
    { id: "Solomon Islands", name: "Solomon Islands", region: "Australasia" },
    { id: "Vanuatu", name: "Vanuatu", region: "Australasia" },
    { id: "Samoa", name: "Samoa", region: "Australasia" },
    { id: "Tonga", name: "Tonga", region: "Australasia" },
    { id: "Micronesia", name: "Micronesia", region: "Australasia" },
    { id: "Palau", name: "Palau", region: "Australasia" },
    { id: "Marshall Islands", name: "Marshall Islands", region: "Australasia" },
    { id: "Kiribati", name: "Kiribati", region: "Australasia" },
    { id: "Nauru", name: "Nauru", region: "Australasia" },
    { id: "Tuvalu", name: "Tuvalu", region: "Australasia" },
  ],
};

// Helper function to get unique countries (in case of duplicates)
const getUniqueCountries = (countries: Country[]): Country[] => {
  const seen = new Set<string>();
  return countries.filter((country) => {
    if (seen.has(country.id)) {
      return false;
    }
    seen.add(country.id);
    return true;
  });
};

export const allCountries: Country[] = getUniqueCountries(Object.values(countriesByRegion).flat());

export const regions = [
  "North America",
  "South America",
  "Europe",
  "Asia",
  "Middle East",
  "Africa",
  "Caribbean",
  "Australasia",
];

